// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 notme contributors
// Origin: lifted from cloister (AGPL-3.0) by sole author, contributed to notme under Apache-2.0 on 2026-05-18; see NOTICE.

// IR → zod TypeScript source.
//
// Emits one zod schema per struct plus a TypeScript type alias derived
// from it. Struct-to-struct references resolve by name; topological
// order is enforced via forward-declaration via `z.lazy(...)`.

use std::fmt::Write as _;

use crate::error::Result;
use crate::ir::{Enum, FieldType, ScalarType, Schema, Struct, StructField, Union};

pub fn emit(schema: &Schema) -> Result<String> {
    let mut out = String::new();
    writeln!(out, "// Generated by schema-bridge — do not edit by hand.").unwrap();
    writeln!(
        out,
        "// Regenerate with `task gen:zod` (runs the schema-bridge plugin)."
    )
    .unwrap();
    writeln!(out, "//").unwrap();
    writeln!(out, "// If schema-bridge errored on a construct used here,").unwrap();
    writeln!(out, "// the codegen needs a new mapping — extend it, don't").unwrap();
    writeln!(out, "// hand-author this file.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, r#"import {{ z }} from "zod";"#).unwrap();
    writeln!(out).unwrap();

    // Enums emit first: no forward references possible (they only
    // reference string literals), and struct field renderers may
    // reference enum schema names.
    for e in &schema.enums {
        emit_enum(&mut out, e);
        writeln!(out).unwrap();
    }

    for s in &schema.structs {
        emit_struct(&mut out, s)?;
        writeln!(out).unwrap();
    }

    Ok(out)
}

fn emit_enum(out: &mut String, e: &Enum) {
    let variants_zod: Vec<String> =
        e.variants.iter().map(|v| format!("\"{v}\"")).collect();
    let variants_ts: Vec<String> =
        e.variants.iter().map(|v| format!("\"{v}\"")).collect();
    writeln!(
        out,
        "export const {name}Schema = z.enum([{joined}]);",
        name = e.name,
        joined = variants_zod.join(", ")
    )
    .unwrap();
    writeln!(out, "export type {name} = {joined};", name = e.name, joined = variants_ts.join(" | "))
        .unwrap();
}

fn emit_struct(out: &mut String, s: &Struct) -> Result<()> {
    // `z.lazy` lets struct refs forward-declare without a topological
    // sort. The cost is one extra closure per schema; the saving is
    // not having to detect cycles.
    writeln!(
        out,
        "export const {name}Schema: z.ZodType<{name}> = z.lazy(() =>",
        name = s.name
    )
    .unwrap();

    match (&s.fields[..], &s.union) {
        // Plain struct: no union.
        (fields, None) => {
            emit_zod_object(out, "  ", fields, None);
            writeln!(out, ");").unwrap();
        }
        // Struct with a union — the union is a NESTED object under
        // its discriminant name, matching capnp's JSON convention
        // (`"kind": { "external": {…} }` for struct variants,
        // `"transport": { "uds": null }` for Void variants). Base
        // fields are siblings of that nested object.
        (fields, Some(u)) => {
            emit_zod_object(out, "  ", fields, Some(u));
            writeln!(out, ");").unwrap();
        }
    }
    writeln!(out).unwrap();

    emit_ts_type(out, s);

    Ok(())
}

// `.strict()` rejects unknown keys at parse time — without it, zod's
// default behavior silently drops them, so an operator typo like
// `holdsCredentials = ["SECRET"]` (extra 's' vs the schema's
// `holdsCredential`) discards the credential without a diagnostic.
// Per cloister-cf2e6a / skeptic N1: the schema-bridge is the boundary
// where typos must become errors. Inner union variants ALSO use
// `.strict()` (see `emit_zod_union` below).
fn emit_zod_object(out: &mut String, indent: &str, fields: &[StructField], union: Option<&Union>) {
    writeln!(out, "{indent}z.object({{").unwrap();
    for field in fields {
        let rendered = render_field(field);
        writeln!(out, "{indent}  {}: {},", field.name, rendered).unwrap();
    }
    if let Some(u) = union {
        write!(out, "{indent}  {disc}: ", disc = u.discriminant_name).unwrap();
        emit_zod_union(out, &format!("{indent}  "), u);
        writeln!(out, ",").unwrap();
    }
    write!(out, "{indent}}}).strict()").unwrap();
}

// Each variant is a single-key object. `z.union([...])` rather than
// `z.discriminatedUnion` because there's no discriminator field
// within the variant — the variant name IS the key. `.strict()`
// ensures each variant rejects keys belonging to its siblings, which
// is the runtime invariant that matches capnp's wire discriminant.
fn emit_zod_union(out: &mut String, indent: &str, u: &Union) {
    writeln!(out, "z.union([").unwrap();
    for variant in &u.variants {
        let inner = match &variant.ty {
            FieldType::Scalar(ScalarType::Void) => "z.null()".to_owned(),
            other => render_zod_type(other),
        };
        writeln!(
            out,
            "{indent}  z.object({{ {name}: {inner} }}).strict(),",
            name = variant.name
        )
        .unwrap();
    }
    write!(out, "{indent}])").unwrap();
}

fn emit_ts_type(out: &mut String, s: &Struct) {
    match (&s.fields[..], &s.union) {
        (fields, None) => {
            writeln!(out, "export interface {} {{", s.name).unwrap();
            for field in fields {
                writeln!(out, "  {}: {};", field.name, render_ts_type(&field.ty)).unwrap();
            }
            writeln!(out, "}}").unwrap();
        }
        (fields, Some(u)) => {
            writeln!(out, "export interface {} {{", s.name).unwrap();
            for field in fields {
                writeln!(out, "  {}: {};", field.name, render_ts_type(&field.ty)).unwrap();
            }
            writeln!(out, "  {}: {};", u.discriminant_name, render_ts_union(u)).unwrap();
            writeln!(out, "}}").unwrap();
        }
    }
}

fn render_ts_union(u: &Union) -> String {
    let mut parts: Vec<String> = Vec::new();
    for variant in &u.variants {
        let inner = match &variant.ty {
            FieldType::Scalar(ScalarType::Void) => "null".to_owned(),
            other => render_ts_type(other),
        };
        parts.push(format!("{{ {name}: {inner} }}", name = variant.name));
    }
    parts.join(" | ")
}

fn render_field(field: &StructField) -> String {
    render_zod_type(&field.ty)
}

fn render_zod_type(t: &FieldType) -> String {
    match t {
        FieldType::Scalar(s) => render_zod_scalar(*s).to_owned(),
        FieldType::StructRef(name) => format!("{name}Schema"),
        FieldType::EnumRef(name) => format!("{name}Schema"),
        FieldType::List(inner) => format!("z.array({})", render_zod_type(inner)),
    }
}

fn render_zod_scalar(s: ScalarType) -> &'static str {
    match s {
        ScalarType::Void => "z.void()",
        ScalarType::Bool => "z.boolean()",
        ScalarType::Int8
        | ScalarType::Int16
        | ScalarType::Int32
        | ScalarType::Int64 => "z.number().int()",
        ScalarType::UInt8
        | ScalarType::UInt16
        | ScalarType::UInt32
        | ScalarType::UInt64 => "z.number().int().nonnegative()",
        ScalarType::Float32 | ScalarType::Float64 => "z.number()",
        ScalarType::Text => "z.string()",
        ScalarType::Data => "z.instanceof(Uint8Array)",
    }
}

fn render_ts_type(t: &FieldType) -> String {
    match t {
        FieldType::Scalar(s) => render_ts_scalar(*s).to_owned(),
        FieldType::StructRef(name) => name.clone(),
        FieldType::EnumRef(name) => name.clone(),
        FieldType::List(inner) => {
            // `T[]` rather than `(T)[]` — TS array postfix is
            // right-associative against itself + scalars + struct
            // refs, so the bare form is unambiguous. When union types
            // land they'll need explicit parens because `A | B[]`
            // parses as `A | (B[])`; handle then, not now.
            format!("{}[]", render_ts_type(inner))
        }
    }
}

fn render_ts_scalar(s: ScalarType) -> &'static str {
    match s {
        ScalarType::Void => "void",
        ScalarType::Bool => "boolean",
        ScalarType::Int8
        | ScalarType::Int16
        | ScalarType::Int32
        | ScalarType::Int64
        | ScalarType::UInt8
        | ScalarType::UInt16
        | ScalarType::UInt32
        | ScalarType::UInt64
        | ScalarType::Float32
        | ScalarType::Float64 => "number",
        ScalarType::Text => "string",
        ScalarType::Data => "Uint8Array",
    }
}
